# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CV Rodrigo Nicolas Carreras - carrerasrodrigo
email: carrerasrodrigo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site where you can find my full CV.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carreras.io" # the base hostname & protocol for your site
twitter_username: carrerasrodrigo
github_username:  carrerasrodrigo

# Build settings
markdown: kramdown
